# Generated by Django 6.0.6 on 2026-07-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
